[v1]
"bat 0.22.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"eureka 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["eureka"]
"nomino 1.2.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["nomino"]
"tectonic 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["tectonic"]
