import = [
    "~/.config/alacritty/themes/themes/hyper.toml"
]
live_config_reload = true
working_directory = "None"

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

  [colors.bright]
  black = "#808080"
  blue = "#0066ff"
  cyan = "#00ffff"
  green = "#33ff00"
  magenta = "#cc00ff"
  red = "#fe0100"
  white = "#FFFFFF"
  yellow = "#feff00"

  [colors.cursor]
  cursor = "#ffffff"
  text = "#F81CE5"

  [colors.normal]
  black = "#000000"
  blue = "#0066ff"
  cyan = "#00ffff"
  green = "#33ff00"
  magenta = "#cc00ff"
  red = "#fe0100"
  white = "#d0d0d0"
  yellow = "#feff00"

  [colors.primary]
  background = "#000000"
  foreground = "#ffffff"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"

[font]
size = 14.0

  [font.normal]
  family = "JetBrainsMonoNL Nerd Font"
  style = "Medium"

  [font.italic]
  family = "JetBrainsMonoNL Nerd Font"
  style = "Italic"

  [font.bold]
  family = "JetBrainsMonoNL Nerd Font"
  style = "SemiBold"

  [font.bold_italic]
  family = "JetBrainsMonoNL Nerd Font"
  style = "Bold Italic"

  [font.offset]
  x = -1
  y = 0

  [font.glyph_offset]
  x = 0
  y = 0

[[keyboard.bindings]]
action = "Paste"
key = "P"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
chars = "gc"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002%"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = """
\u000e
"""
key = "N"
mods = "Control"

[[mouse.bindings]]
action = "Copy"
mouse = "Middle"

[scrolling]
history = 5000
multiplier = 1

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
program = "/usr/bin/zsh"

[window]
dynamic_padding = false
opacity = 0.9
padding = { x = 1, y = 0 }
title = "Alacritty"

  [window.class]
  general = "Alacritty"
  instance = "Alacritty"
