#!/bin/sh
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Tmux
alias tmux-restart='tmux kill-server && tmux'

# Pacman
alias refresh='sudo pacman -Syy'
alias update='sudo pacman -Syu'

# Sudo
alias sudo='nocorrect sudo -E'
# alias sudo='doas'
# alias sudoedit='doas rnano'

# confirm before overwriting something
alias rm='rm -i'
alias cp='advcp -gu'
alias mv='advmv -gu'

# bat
# alias cat='bat'

#node-versions
alias ns='~/.scripts/node/node-switch.sh'

#anime-cli
alias anime-cli='anipy-cli -d -o -q 1080'

#xrandr brightness
alias br='xrandr --output VGA-0 --brightness '

#xsel
alias xsel-copy='xsel --clipboard'

# nnn
alias n='nnn -dr'
alias N='sudo nnn -drx'

#brightness
alias set-br='sudo set-brightness.sh'

# neovim
alias nv='nvim'
alias Nv='sudo nvim'

#feh
alias feh-display='feh -d -. Wallpapers'

# git
alias gcl='git clone'
alias gco='git checkout'
alias gm='git merge'

# Vanaheim HDD
alias vanaheim='sudo mount /dev/sdb1 /home/eric/Yggdrasil'
alias uvanaheim='sudo umount /dev/sdb1 /home/eric/Yggdrasil'

# Youtube
alias yt='yt-dlp --config-location /home/eric/.config/yt-dlp/config'
alias ytp='yt-dlp --config-location /home/eric/.config/yt-dlp/config1'
alias yta='yt-dlp --config-location /home/eric/.config/yt-dlp/config3'
alias ytpa='yt-dlp --config-location /home/eric/.config/yt-dlp/config4'
alias clear-yt='echo -n "" > /home/eric/youtube.txt'
alias ytfzf='ytfzf --sort-by=upload_date'

#Aria
alias clear-aria='echo -n "" > /home/eric/.aria2/input.conf'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# ls
alias ls='exa --long --tree --level=1'
alias lt='exa --tree --level=2'

# display off
alias screenoff='xset dpms force off && betterlockscreen -l'
alias sleep='sudo systemctl suspend && betterlockscreen -l'

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"

#Tv-Shows
alias peaky-blinders="mpv $HOME/Tv-Shows/Peaky\ Blinders"
# Anime Aliases
# Boku No Hero Academia
alias boku-no-hero="mpv $HOME/Anime/Shows/Boku\ no\ Hero"

# Hunter X Hunter
alias hunter-x-hunter="mpv --sub-scale=1.1 $HOME/Anime/Shows/Hunter\ X\ Hunter"

# Naruto Shippuden
alias naruto-shippuden="mpv $HOME/Anime/Shows/Naruto\ Shippuden"
