#!/bin/sh
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'
alias zshrc='nvim ~/.config/zsh/'

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Tmux
alias tmux-restart='tmux kill-server && tmux'

# Changing "ls" to "exa"
alias ls='exa -al --color=always --group-directories-first' # my preferred listing
alias la='exa -a --color=always --group-directories-first'  # all files and dirs
alias ll='exa -l --color=always --group-directories-first'  # long format
alias lt='exa -aT --color=always --group-directories-first' # tree listing
alias l.='exa -a | egrep "^\."'

# pacman and yay
alias pacsyu='sudo pacman -Syu'                  # update only standard pkgs
alias pacsyyu='sudo pacman -Syyu'                # Refresh pkglist & update standard pkgs
alias yaysua='yay -Sua --noconfirm'              # update only AUR pkgs (yay)
alias yaysyu='yay -Syu --noconfirm'              # update standard pkgs and AUR pkgs (yay)
alias parsua='paru -Sua --noconfirm'             # update only AUR pkgs (paru)
alias parsyu='paru -Syu --noconfirm'             # update standard pkgs and AUR pkgs (paru)
alias unlock='sudo rm /var/lib/pacman/db.lck'    # remove pacman lock
alias cleanup='sudo pacman -Rns $(pacman -Qtdq)' # remove orphaned packages

# Sudo
alias sudo='nocorrect sudo -E'
# alias sudo='doas'
# alias sudoedit='doas rnano'

# confirm before overwriting something
alias rm='rm -i'
alias cp='advcp -gu'
alias mv='advmv -gu'

# bat
alias cat='bat'

#node-versions
# alias ns='~/.scripts/node/node-switch.sh'

#anime-cli
alias anime-cli='anipy-cli -D -o -q 1080'

#xrandr brightness
alias br='xrandr --output VGA-0 --brightness '

#xsel
alias xsel-copy='xsel --clipboard'

# nnn
alias n='nnn -dr'
alias N='sudo nnn -drx'

#brightness
alias set-br='sudo set-brightness.sh'

# neovim
alias nv='nvim'
alias Nv='sudo nvim'

#feh
alias feh-display='feh -d -.'

# git
alias gcl='git clone'
alias gco='git checkout'
alias gm='git merge'

# Vanaheim HDD
# alias vanaheim='sudo mount -t btrfs -o noatime,commit=120,compress=zstd,space_cache=v2 /dev/sdb1 /home/eric/Yggdrasil'
alias vanaheim='sudo mount -t btrfs /dev/sdb1 /home/eric/Yggdrasil'
alias uvanaheim='sudo umount /dev/sdb1 /home/eric/Yggdrasil'
# alias vanaheim='sudo mount -o noatime,commit=120,compress=zstd,space_cache,ssd,subvol=@,clear_cache /home/eric/Yggdrasil'

# Youtube
alias yt='yt-dlp --config-location /home/eric/.config/yt-dlp/normal-config'
alias ytp='yt-dlp --config-location /home/eric/.config/yt-dlp/playlist-config'
alias yta='yt-dlp --config-location /home/eric/.config/yt-dlp/audio-config'
alias clear-yt='echo -n "" > /home/eric/youtube.txt'
alias yt-download='yt -a /home/eric/youtube.txt'

#Aria
alias clear-aria='echo -n "" > /home/eric/.aria2/input.conf'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# display off
alias screenoff='xset dpms force off && betterlockscreen -l'
alias sleep='sudo systemctl suspend && betterlockscreen -l'

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"

# Anime Aliases
# Boku No Hero Academia
alias boku-no-hero="mpv $HOME/Anime/Shows/Boku\ no\ Hero"

# Hunter X Hunter
alias hunter-x-hunter="mpv $HOME/Anime/Shows/Hunter\ X\ Hunter"

# Naruto Shippuden
alias naruto-shippuden="mpv $HOME/Anime/Shows/Naruto\ Shippuden"

alias clear-buckets="aws s3 rm s3://b2voiprectest --recursive --endpoint-url=https://s3.us-west-000.backblazeb2.com --profile ericjohnson-backblaze-rw && aws s3 rm s3://voiprectest --recursive --endpoint-url=$BIFROST_ENDPOINT_URL --profile ericjohnson-bifrost-rw"

alias colormysql=$(echo -e 'mysql --prompt="\x1B[31m\\u\x1B[34m@\x1B[32m\\h\x1B[0m:\x1B[36m\\d>\x1B[0m "')
