#!/bin/sh
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Tmux
alias tmux-restart='tmux kill-server && tmux'

# Pacman
alias refresh='doas pacman -Syyy'
alias upgrade='doas pacman -Syu'

# Sudo
alias sudo='nocorrect sudo -E'

# confirm before overwriting something
alias rm='rm -i'
alias cp='advcp -gu'
alias mv='advmv -gu'

#node-versions
alias ns='~/.scripts/node/node-switch.sh'

#anime-cli
alias anime-cli='anipy-cli -d -o -q 1080'

#xrandr brightness
alias br='xrandr --output VGA-0 --brightness '

# nnn
alias n='nnn -dr'
alias N='doas nnn -drx'

#brightness
alias set-br='doas set-brightness.sh'

# neovim
alias nv='nvim'
alias Nv='doas nvim'
alias lv='lvim'
alias Lv='doas lvim'

#feh
alias feh-display='feh -d -. Wallpapers'

# git
alias gcl='git clone'

# Vanaheim HDD
alias vanaheim='doas mount /dev/sdb1 /mnt/Vanaheim'
alias uvanaheim='doas umount /dev/sdb1 /mnt/Vanaheim'

# Youtube
alias yt='yt-dlp --config-location /home/eric/.config/yt-dlp/config'
alias ytp='yt-dlp --config-location /home/eric/.config/yt-dlp/config1'
alias yta='yt-dlp --config-location /home/eric/.config/yt-dlp/config3'
alias ytpa='yt-dlp --config-location /home/eric/.config/yt-dlp/config4'
alias clear-yt='echo -n "" > /home/eric/youtube.txt'

#Aria
alias clear-aria='echo -n "" > /home/eric/.aria2/input.conf'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# ls
alias ls='exa --long --tree --level=1'

# display off
alias screenoff='xset dpms force off && betterlockscreen -l'
alias sleep='doas systemctl suspend && betterlockscreen -l'

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"

#Anime
alias naruto="mpv $HOME/Media/Anime/Shows/Naruto"

#zathura
alias z="zathura"
