#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
# export PATH=$HOME/.local/share/go/bin:$PATH
# export PATH=$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH
export PATH=/usr/bin/python3:$PATH
export PATH=/usr/bin/aws_completer:$PATH
# export PATH=/usr/bin/luarocks:$PATH
# export PATH=/usr/bin/gem:$PATH
# export GOPATH=$HOME/.local/share/go
# export PATH=~/.npm-global/bin:$PATH
# export PATH=$HOME/.fnm:$PATH
# export PATH=$HOME/.rvm/bin:$PATH
export PATH=$HOME/.go/bin:$PATH
export PATH=$HOME/.scripts/aws-s3-integrity-check:$PATH
export PATH=$HOME/.scripts/clearcache:$PATH
export PATH=$HOME/.scripts/ffmpeg-bulk:$PATH
export PATH=$HOME/.scripts/library:$PATH
export PATH=$HOME/.scripts/mysql:$PATH
export PATH=$HOME/.scripts/pacman:$PATH
export PATH=$HOME/.scripts/pass-gen:$PATH
export PATH=$HOME/.scripts/performance:$PATH
export PATH=$HOME/.scripts/public-ip-address:$PATH
export PATH=$HOME/.scripts/weather:$PATH
export PATH=$HOME/.scripts/node/node-switch.sh:$PATH
export PATH=$HOME/.zshrc:$PATH
# export PATH=$HOME/.npm-global/bin:$PATH
export PATH=~/.npm-global/bin:$PATH
export NNN_PLUG='r:renamer'
# export NNN_COLORS='#27272727'
export NNN_FCOLORS='c1e2272e006033f7c6d6abc4'
export NNN_ARCHIVE="\\.(7z|bz2|gz|tar|tgz|zip)$"
export NNN_BMS="a:$HOME/Media/Anime;d:$HOME/Media/Aria;m:$HOME/Media/Music;y:$HOME/Media/YouTube"
export NNN_TRASH=1

#taskd
export TASKDDATA=/var/taskd

#AWS_EXPORTS
export AWS_PROFILE='default'
export AWS_STATUS=$HOME/.scripts/aws-s3-integrity-check/aws-check-status.sh
export AWS_BACKUP=$HOME/Git/Development/Clients/ctgreno/05-09-2022-test-01/uploads/
export AWS_BUCKET='ericngigi-test'
export AWS_SYNC="$AWS_STATUS $AWS_BACKUP $AWS_BUCKET /"
export AWS_LOGS=$HOME/Git/Development/Clients/ctgreno/05-09-2022-test-01/logs/upload-log
