#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch2.sh
# picom --config /home/eric/.config/picom/picom.conf &

# bspc monitor LVDS -d 1 2 3 4 5
bspc monitor VGA-0 -d 1 2 3 4 5 6 7 8

##--Global Settings--##
bspc config focused_border_color    "#0066ff" 
bspc config normal_border_color     "#adb8b8"
bspc config active_border_color     "#adb8b8"
bspc config presel_feedback_color   "#327bd1"

##--Monitor and Desktop Settings--##
bspc config top_padding           32
bspc config bottom_padding        6
bspc config left_padding          2
bspc config right_padding         2
bspc config border_width          2
bspc config window_gap            10
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config single_monocle        false
bspc config focus_by-distance     true
bspc config history_aware_focus   true

# bspc rule -a Zathura state=fullscreen
# bspc rule -a Atril state=fullscreen
bspc rule -a mpv desktop=^1
bspc rule -a Brave-browser desktop=^2
bspc rule -a qBittorrent desktop=^3
bspc rule -a Clementine desktop=^3
bspc rule -a TIPP10 desktop=^3
bspc rule -a TelegramDesktop desktop=^4
bspc rule -a thunderbird desktop=^4
