#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor LVDS -d 1 2 3
bspc monitor VGA-0 -d 4 5 6 

##--Global Settings--##
bspc config focused_border_color "#048df4" 
bspc config normal_border_color  "#ff0000"
bspc config active_border_color "#1e1e1e"
bspc config presel_feedback_color "#327bd1"
bspc config urgent_border_color "#dd2727"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
##bspc config merge_overlapping_monitors true

##--Monitor and Desktop Settings--##
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 12

bspc rule -a Zathura state=fullscreen
bspc rule -a mpv state=fullscreen
bspc rule -a Brave-browser desktop=^2
bspc rule -a firefoxdeveloperedition desktop=^2
bspc rule -a qBittorrent desktop=^3
bspc rule -a mpv desktop=^4
