Net/ThemeName "Breeze-Dark"
Net/IconThemeName "breeze-dark"
Gtk/CursorThemeName "breeze_cursors"
Gtk/CursorThemeSize 26
Gtk/FontName "Roboto Medium 12"
Net/EnableEventSounds 0
Net/EnableInputFeedbackSounds 0
