#!/bin/bash - 

[[ $DEBUG ]] && set -o nounset
set -o pipefail -o errexit -o errtrace
trap 'echo -e "${FMT_BOLD}ERROR${FMT_OFF}: at $FUNCNAME:$LINENO"' ERR

readonly PROGRAM_NAME="${0##*/}"
readonly SCRIPT_NAME="${0##*/}"

readonly FMT_BOLD='\e[1m'
readonly FMT_UNDERL='\e[4m'
readonly FMT_OFF='\e[0m'

readonly ERR_NO_CMD=60

FORCE_EXEC=
readonly F_WORKLIST='/tmp/ffmpegbulk_list'
F_FFMPEG_SCRIPT='./ffmpeg_cmd.sh'
F_LIST=
ARGSIN=
ARGSOUT=
EXTIN=
EXTOUT=


# $1 = command to test (string)
fn_need_cmd() {
    if ! command -v "$1" > /dev/null 2>&1
        then fn_err "need '$1' (command not found)" $ERR_NO_CMD
    fi
}
# $1 = message (string)
m_say() {
    echo -e "$PROGRAM_NAME: $1"
}
# $1 = error message (string), $2 = return code (int)
fn_err() {
    m_say "${FMT_BOLD}ERROR${FMT_OFF}: $1" >&2
    exit $2
}

fn_show_params() {
    m_say "list file is: $F_LIST, -xi: $EXTIN, -xo: $EXTOUT, -ai: $ARGSIN, -ao: $ARGSOUT, -o: $F_FFMPEG_SCRIPT" >&2
}

fn_need_cmd "sed"
fn_need_cmd "gawk"
fn_need_cmd "ffmpeg"
fn_need_cmd "tee"

if test -z "$*"; then
    fn_help
    exit
else
    # Individually check provided args
    while test -n "$1" ; do
        case $1 in
            "--help"|"-h")
                fn_help
                exit
                ;;
            "--extin"|"-xi")
                EXTIN=$2
                shift
                ;;
            "--extout"|"-xo")
                EXTOUT=$2
                shift
                ;;
            "--argsin"|"-ai")
                ARGSIN=$2
                shift
                ;;
            "--argsout"|"-ao")
                ARGSOUT=$2
                shift
                ;;
            "--outfile"|"-o")
                F_FFMPEG_SCRIPT="$2"
                shift
                ;;
            "--execute"|"-e")
                FORCE_EXEC=1
                ;;
            *)
		# TODO: check that file exists, exit if not
		[[ -e "$1" ]] || { echo "file '$1' does not exist"; exit 127; }
                F_LIST="$1"
                ;;
        esac	# --- end of case ---
        # Delete $1
        shift
    done
fi

if test "$F_LIST" = ""; then
    fn_err "no list file provided !"
fi

[[ $DEBUG ]] && fn_show_params

cp "$F_LIST" "$F_WORKLIST" || exit

sed -i "s/$EXTIN//" "$F_WORKLIST"

m_say "generating script as follows:"
echo "# Script generated by $PROGRAM_NAME
# Press CTRL+C (^C) to exit the script while in execution" > "$F_FFMPEG_SCRIPT"
gawk -v v_xi="$EXTIN" -v v_xo="$EXTOUT" -v v_ai="$ARGSIN" -v v_ao="$ARGSOUT" '{print "ffmpeg "v_ai" -i \""$0 v_xi"\" "v_ao" \""$0 v_xo"\" || exit"}' "$F_WORKLIST" | tee -a "$F_FFMPEG_SCRIPT"

m_say "script generated"
m_say "granting execution permission..."
chmod ug+x "$F_FFMPEG_SCRIPT"
m_say "script \"$F_FFMPEG_SCRIPT\" now ready to be executed"

# isn't that part messy asf fam?
if [[ $FORCE_EXEC ]]; then
#     # if relative path to F_FFMPEG_SCRIPT, make it absolute
#     if test "$(basename "$F_FFMPEG_SCRIPT")" = "$F_FFMPEG_SCRIPT"; then
#         F_FFMPEG_SCRIPT="$(pwd)/$F_FFMPEG_SCRIPT"
#         #m_say "corrected script name : $F_FFMPEG_SCRIPT"
#     fi
#     "$F_FFMPEG_SCRIPT"
#     rm -i "$F_FFMPEG_SCRIPT" "$F_LIST"
    trap "rm -i '$F_FFMPEG_SCRIPT' '$F_LIST'" EXIT
    /bin/bash "$F_FFMPEG_SCRIPT" 
fi

exit
