reload "user.options"
reload "user.keybindings"
reload "user.plugins"
reload "user.nvimtree"
reload "user.colorizer"
-- reload "user.icons"
reload "user.treesitter"
reload "user.lsp"
-- reload "user.server"
